---
title: "Untitled"
author: "Georgios Karamanis"
date: "9/16/2021"
output: html_document
resource_files:
  - '.'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r read_data, echo=FALSE, message=FALSE, cache=TRUE}
library(tidyverse)
library(lubridate)
library(crosstalk)
library(reactable)
library(htmltools)

billboard <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-09-14/billboard.csv')

audio_features <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-09-14/audio_features.csv')

billb_feat <- billboard %>% 
  left_join(audio_features) %>% 
  mutate(
    week_id = mdy(week_id),
    year = year(week_id),
    month = month(week_id)
    ) %>% 
  select(performer, song, week_id, year, month, week_position, previous_week_position, weeks_on_chart, spotify_track_preview_url, song_id) %>% 
  filter(year == 2021)
```

```{r table, echo=FALSE, message=FALSE}
shared_data <- SharedData$new(billb_feat)

shared_songs <- SharedData$new(billb_feat, group = shared_data$groupName())

tbl <- reactable(
  shared_data,
  class = "songs-tbl"
)
```

```{r output, echo=FALSE}
div(
  class = "songs",
  tbl
)
```
